[tox]
envlist = lint, test, docs
requires =
    tox-uv>=1

[testenv:lint]
runner = uv-venv-lock-runner
extras = dev
commands =
    ruff check .
    ruff format --check .

[testenv:test]
runner = uv-venv-lock-runner
extras = test
commands = pytest --cov=src --cov-report=xml {posargs}

[testenv:docs]
runner = uv-venv-lock-runner
extras = docs
commands =
    make -C docs html
