[tox]
envlist = django{42,52}, lint, docs
requires = tox-uv>=1

[testenv:lint]
runner = uv-venv-lock-runner
extras = dev
commands =
    ruff check .
    ruff format --check .

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    django42: django42
    django52: test
commands = pytest --cov=src --cov-report=xml {posargs}

[testenv:docs]
runner = uv-venv-lock-runner
basepython = python3.12
changedir = {toxinidir}/docs
dependency_groups = doc
allowlist_externals = make
commands =
    make html
