name: CI

on:
  push:
    branches: [main]
  pull_request:
  # Allow this workflow to be called from other workflows
  workflow_call:

jobs:
  run_tests:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        toxenv: [lint, docs, django42, django52]

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: Install CI dependencies
        run: uv sync --group ci

      - name: Run tox
        run: uv run tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        if: matrix.toxenv == 'django42'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
